Temp
AkashBoora/blinkist-react pull request #1
Opened 2022-09-05 05:39 UTC by AkashBoora

Please review the code.

2022-09-05 05:45 UTC, Nisanth-Chilakamarri-ZeMoSo commented on src/components/molecules/BookCard/BookCard.tsx
> +const buttonPropTypes = {
Refactor this component, molecules should not have this. Try to have enums declared to store the defaults

2022-09-05 05:50 UTC, Nisanth-Chilakamarri-ZeMoSo commented on src/components/organisam/Footer/Footer.tsx
> +import { FooterNavListComponent } from "../../molecules/FooterNavList/FooterNavList";
Why is this in organisms?

2022-09-05 05:54 UTC, Nisanth-Chilakamarri-ZeMoSo commented on src/components/pages/BookDetailsPage/BookDetails.tsx
> +  const [bookData, setBookData] = useState<Book>();
This is not a page component, this is an organism

2022-09-05 05:55 UTC, Nisanth-Chilakamarri-ZeMoSo commented on src/components/pages/BookDetailsPage/BookDetails.tsx
> +      .catch((error: any) => console.log(error));
try to move the axios calls to separate folder API, call the appropriate API whenever needed

2022-09-05 05:56 UTC, Nisanth-Chilakamarri-ZeMoSo commented on src/components/pages/CategoryResultsPage/CategoryResults.tsx
> +    axios
Same, this is not a page component. Move all Axios calls to different folder

2022-09-05 05:56 UTC, Nisanth-Chilakamarri-ZeMoSo commented on src/components/pages/ExplorePage/ExplorePage.tsx
> +      .then((res: any) => {
same

2022-09-05 05:56 UTC, Nisanth-Chilakamarri-ZeMoSo commented on src/components/pages/MyLibraryPage/MyLibrary.tsx
> +
same

2022-09-06 09:12 UTC, Nisanth-Chilakamarri-ZeMoSo requested changes

2022-09-06 09:12 UTC, Nisanth-Chilakamarri-ZeMoSo commented on src/components/organisam/BookDetails/BookDetails.tsx
> +    console.log("passed id",id);
remove all console logs

2022-09-06 09:12 UTC, Nisanth-Chilakamarri-ZeMoSo commented on src/components/organisam/Footer/Footer.tsx
> +import { FooterNavListComponent } from "../../molecules/FooterNavList/FooterNavList";
move this to molecules

2022-09-06 09:32 UTC, Nisanth-Chilakamarri-ZeMoSo commented
Resolve the code smells

2022-09-06 10:09 UTC, AkashBoora commented
Nisanth Please check now!

2022-09-06 10:11 UTC, Nisanth-Chilakamarri-ZeMoSo approved these changes

2022-09-07 05:56 UTC, merged